export enum RoutePath {
  HOME = '/',
  LOGIN = 'login',
  SIGNUP = 'signup',
  EMPLOYEES = 'employees',
  PROFILE = 'profile',
  PROJECTS = 'projects',
  CVS = 'cvs',
  DEPARTMENTS = 'departments',
  POSITIONS = 'positions',
  SKILLS = 'skills',
  LANGUAGES = 'languages',
  ERROR = 'error',
  GENERAL = '*',
  DETAILS = 'details',
}
